apiVersion: v1
kind: Service
metadata:
  name: ki-coach-frontend
  namespace: ki-coach-frontend
spec:
  selector:
    app: ki-coach-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000