apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8up-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://k8up-io.github.io/k8up
      chart: k8up
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/K8up/values.yaml
    - repoURL: https://github.com/t-foerst/k8s-cluster.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: k8up
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
