apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc-config.yaml
  - pvc-metadata.yaml
  - pvc-audiobooks.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml