apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abs-config
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-ssd