apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: nextcloud
data:
  custom.config.php: |
    <?php
    $CONFIG = array(
      'trusted_domains' => ['localhost', 'cloud.foerst.haus'],
      'overwriteprotocol' => 'https',
      'overwrite.cli.url' => 'https://cloud.foerst.haus',
      'default_phone_region' => 'DE',
      'loglevel' => 2,
      'maintenance_window_start' => 1,
      'trusted_proxies' => ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16'],
      'forwarded_for_headers' => ['HTTP_X_FORWARDED_FOR'],
    );
