apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data-nfs
spec:
  capacity:
    storage: 3Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
    - noatime
  nfs:
    server: 10.10.20.220
    path: /mnt/flex/nextcloud-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Ti
  storageClassName: ""
  volumeName: nextcloud-data-nfs
