apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
  namespace: homarr
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      containers:
        - name: homarr
          image: ghcr.io/homarr-labs/homarr:v1.59.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7575
          env:
            - name: SECRET_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: homarr-secret
                  key: SECRET_ENCRYPTION_KEY
          volumeMounts:
            - name: homarr-data
              mountPath: /appdata
      volumes:
        - name: homarr-data
          persistentVolumeClaim:
            claimName: homarr-data
