env:
  TZ: Europe/Berlin

envSecrets:
  dbEncryption:
    existingSecret: homarr-secret
    key: SECRET_ENCRYPTION_KEY

persistence:
  homarrDatabase:
    enabled: true
    name: homarr-data
    storageClassName: longhorn-ssd
    accessMode: ReadWriteOnce
    size: 100Mi
    mountPath: /appdata

ingress:
  enabled: true
  ingressClassName: traefik-internal
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
  hosts:
    - host: dash.foerst.haus
      paths:
        - path: /
  tls:
    - secretName: homarr-tls
      hosts:
        - dash.foerst.haus

rbac:
  enabled: true
