apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: immich-upload
  namespace: immich
spec:
  buffering:
    maxRequestBodyBytes: 0
    maxResponseBodyBytes: 0
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: immich-headers
  namespace: immich
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: immich-transport
  namespace: immich
spec:
  forwardingTimeouts:
    responseHeaderTimeout: 0s
    idleConnTimeout: 0s
