apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc-data.yaml
  - pvc-media.yaml
  - pvc-db.yaml
  - deployment-db.yaml
  - deployment-redis.yaml
  - deployment-paperless.yaml
  - service-db.yaml
  - service-redis.yaml
  - service-paperless.yaml
  - ingress.yaml