apiVersion: apps/v1
kind: Deployment
metadata:
  name: ki-coach-backend
  namespace: ki-coach
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ki-coach-backend
  template:
    metadata:
      labels:
        app: ki-coach-backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: ki-coach-backend
          image: ghcr.io/kaiolefoerst-collab/kicoach_python:fd73c071ff5230e18299d6971df0bc6162927cda
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ki-coach-secrets
                  key: GEMINI_API_KEY