apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-nfs
spec:
  capacity:
    storage: 3Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
    - noatime
  nfs:
    server: 10.10.20.220
    path: /mnt/Media/jellyfin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Ti
  storageClassName: ""
  volumeName: jellyfin-media-nfs
