apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: audiobookshelf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/t-foerst/k8s-cluster.git
    targetRevision: HEAD
    path: Audiobookshelf
  destination:
    server: https://kubernetes.default.svc
    namespace: audiobookshelf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
