resources:
  - headlamp.yaml
  - arr.yaml
  - immich.yaml
  - dokuwiki.yaml
  - vaultwarden.yaml
  - homarr.yaml
  - paperless-ngx.yaml
  - audiobookshelf.yaml
  - jellyfin.yaml
  - metallb-operator.yaml
  - metallb-config.yaml
  - nextcloud.yaml
  - kube-vip.yaml
  - traefik-crds.yaml
  - traefik-internal.yaml
  - traefik-external.yaml
