apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-game
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/t-foerst/k8s-cluster.git
    targetRevision: HEAD
    path: MLGame
  destination:
    server: https://kubernetes.default.svc
    namespace: ml-game
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
