apiVersion: v1
kind: PersistentVolume
metadata:
  name: arr-downloads-nfs
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
    - noatime
  nfs:
    server: 10.10.20.220
    path: /mnt/Media/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arr-downloads
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: ""
  volumeName: arr-downloads-nfs
